/**
 * DUO RAMPAGE: DHAKA PARKOUR - Campaign Level Metadata Definitions
 * Based on Dhaka-Parkour.md Section 10 & 34
 */

export interface ParkourLevelMeta {
  id: string;
  levelNumber: number;
  name: string;
  targetTime: string;
  targetSeconds: number;
  mood: 'day_rooftop' | 'sunset' | 'night' | 'rain' | 'storm' | 'chase';
  environmentName: string;
  description: string;
  unlockedByDefault: boolean;
  totalCheckpoints: number;
  totalCoins: number;
  totalStars: number;
  secretEmblemName: string;
}

export const PARKOUR_CAMPAIGN_LEVELS: ParkourLevelMeta[] = [
  {
    id: 'parkour_01',
    levelNumber: 1,
    name: 'Rooftop Introduction',
    targetTime: '5:00',
    targetSeconds: 300,
    mood: 'day_rooftop',
    environmentName: 'Dhaka Summer Rooftops',
    description: 'Learn urban flow: sprint, jump, slide under water tanks, and conquer your first gap.',
    unlockedByDefault: true,
    totalCheckpoints: 3,
    totalCoins: 80,
    totalStars: 3,
    secretEmblemName: 'Rooftop Pioneer',
  },
  {
    id: 'parkour_02',
    levelNumber: 2,
    name: 'Old Dhaka Rooftops',
    targetTime: '5:00',
    targetSeconds: 300,
    mood: 'sunset',
    environmentName: 'Puran Dhaka Skyline',
    description: 'Master double jump, wall slide, and rooftop vault across narrow historical brick buildings.',
    unlockedByDefault: false,
    totalCheckpoints: 4,
    totalCoins: 100,
    totalStars: 3,
    secretEmblemName: 'Old Town Phantom',
  },
  {
    id: 'parkour_03',
    levelNumber: 3,
    name: 'Market Escape',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'day_rooftop',
    environmentName: 'Bustling Bazaar',
    description: 'Slide through awnings, sprint over stalls, and coordinate with partner to unlock dual gates.',
    unlockedByDefault: false,
    totalCheckpoints: 4,
    totalCoins: 120,
    totalStars: 3,
    secretEmblemName: 'Bazaar Speedster',
  },
  {
    id: 'parkour_04',
    levelNumber: 4,
    name: 'Construction Zone',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'day_rooftop',
    environmentName: 'Metro Rail Scaffold',
    description: 'High-wire traversal: wall run along concrete girders, swing on cables, and climb elevators.',
    unlockedByDefault: false,
    totalCheckpoints: 4,
    totalCoins: 130,
    totalStars: 3,
    secretEmblemName: 'Girder Master',
  },
  {
    id: 'parkour_05',
    levelNumber: 5,
    name: 'Highway Crossing',
    targetTime: '5:00',
    targetSeconds: 300,
    mood: 'sunset',
    environmentName: 'Elevated Expressway',
    description: 'Fast-paced timing: sprint over traffic, hurdle barriers, and leap across bridge spans.',
    unlockedByDefault: false,
    totalCheckpoints: 4,
    totalCoins: 110,
    totalStars: 3,
    secretEmblemName: 'Speedway Blitz',
  },
  {
    id: 'parkour_06',
    levelNumber: 6,
    name: 'Rainy Night',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'rain',
    environmentName: 'Neon Wet District',
    description: 'Cinematic rain showcase: neon reflections, high-speed ziplines, and atmospheric lightning.',
    unlockedByDefault: false,
    totalCheckpoints: 5,
    totalCoins: 140,
    totalStars: 3,
    secretEmblemName: 'Neon Shadow',
  },
  {
    id: 'parkour_07',
    levelNumber: 7,
    name: 'Industrial District',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'night',
    environmentName: 'Warehouse Complex',
    description: 'Moving container platforms, steam pipes, conveyors, and separate cooperative routes.',
    unlockedByDefault: false,
    totalCheckpoints: 5,
    totalCoins: 150,
    totalStars: 3,
    secretEmblemName: 'Factory Runner',
  },
  {
    id: 'parkour_08',
    levelNumber: 8,
    name: 'Riverfront',
    targetTime: '5:00',
    targetSeconds: 300,
    mood: 'sunset',
    environmentName: 'Buriganga Docks',
    description: 'Leap across docked cargo ships, crane hooks, and long ziplines over water.',
    unlockedByDefault: false,
    totalCheckpoints: 4,
    totalCoins: 120,
    totalStars: 3,
    secretEmblemName: 'River Drifter',
  },
  {
    id: 'parkour_09',
    levelNumber: 9,
    name: 'Bridge Run',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'chase',
    environmentName: 'Suspension Bridge Superstructure',
    description: 'Pure high-speed adrenaline: continuous sprint, falling deck plates, and gale-force wind.',
    unlockedByDefault: false,
    totalCheckpoints: 5,
    totalCoins: 160,
    totalStars: 3,
    secretEmblemName: 'Cable Walker',
  },
  {
    id: 'parkour_10',
    levelNumber: 10,
    name: 'Skyline Chase',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'chase',
    environmentName: 'Commercial High-Rises',
    description: 'Non-stop rooftop velocity: dash leaps, moving cranes, and zero downtime.',
    unlockedByDefault: false,
    totalCheckpoints: 5,
    totalCoins: 170,
    totalStars: 3,
    secretEmblemName: 'Apex Acrobat',
  },
  {
    id: 'parkour_11',
    levelNumber: 11,
    name: 'Storm Run',
    targetTime: '6:00',
    targetSeconds: 360,
    mood: 'storm',
    environmentName: 'Thunderstorm Outpost',
    description: 'Heavy lightning, collapsing steel scaffolding, electric spark hazards, and team routes.',
    unlockedByDefault: false,
    totalCheckpoints: 5,
    totalCoins: 180,
    totalStars: 3,
    secretEmblemName: 'Thunder Stride',
  },
  {
    id: 'parkour_12',
    levelNumber: 12,
    name: 'Final Tower',
    targetTime: '7:00',
    targetSeconds: 420,
    mood: 'sunset',
    environmentName: 'Dhaka Titan Spire',
    description: 'The vertical climax: climb from street level to the skyscraper pinnacle for the ultimate jump.',
    unlockedByDefault: false,
    totalCheckpoints: 6,
    totalCoins: 250,
    totalStars: 3,
    secretEmblemName: 'Skyline Sovereign',
  },
  {
    id: 'parkour_mega_ramp',
    levelNumber: 99,
    name: 'Mega Ramp Skyline Overdrive',
    targetTime: '4:00',
    targetSeconds: 240,
    mood: 'sunset',
    environmentName: 'Dhaka Mega Ramp & Skyline Chasm',
    description: 'Supersonic gravity-defying ski ramps, aerial boost launchers, Sentinel Drones, and Cyborg Enforcers!',
    unlockedByDefault: true,
    totalCheckpoints: 4,
    totalCoins: 120,
    totalStars: 3,
    secretEmblemName: 'Apex Stratosphere',
  },
];

export const PARKOUR_MEGA_RAMP_META: ParkourLevelMeta = {
  id: 'parkour_mega_ramp',
  levelNumber: 99,
  name: 'Mega Ramp Skyline Overdrive',
  targetTime: '4:00',
  targetSeconds: 240,
  mood: 'sunset',
  environmentName: 'Dhaka Mega Ramp & Skyline Chasm',
  description: 'Supersonic gravity-defying ski ramps, aerial boost launchers, Sentinel Drones, and Cyborg Enforcers!',
  unlockedByDefault: true,
  totalCheckpoints: 4,
  totalCoins: 120,
  totalStars: 3,
  secretEmblemName: 'Apex Stratosphere',
};
